### ISSUE TITLE
Unable to add vanilo admin via composer

### ISSUE THREAD

**Issue by towoju5** [vanilophp/admin#1]
`[InvalidArgumentException]
  Could not find a matching version of package vanilo/admin. Check the package spelling, your version constraint and that the package is available in   
  a stability which matches your minimum-stability (dev).`

I keep getting the above error. I checked on package gist and I couldn't find any package with the name vanilo/admin

**Comment by fulopattila122** [comment]
This should have been solved since then because the final versions have been released:
https://vanilo.io/news/vanilo-admin-30-released

Please feel free to reopen if the issue still persists.
