### ISSUE TITLE
Incomplete documentation for : php artisan make:superuser

### ISSUE THREAD

**Issue by MallauryGerard** [vanilophp/admin#5]
Hello,

This command does not work if you follow the documentation. 
It is necessary to include the Trait "HasRoles" in the User model if we extend it with "\Konekt\User\Models\User".

Like this :
`use HasApiTokens, HasFactory, Notifiable, HasRoles;`

Otherwise, this error message appears :
`Call to undefined method App\Models\User::assignRole()`

**Comment by fulopattila122** [comment]
As far as I see, the documentation says to extend `\Konekt\AppShell\Models\User` and **not `\Konekt\User\Models\User`**:

![image](https://user-images.githubusercontent.com/1162360/221364985-813a3e6f-a670-4757-a29a-0e17de0e6729.png)

Additionally, for variant 2, the usage of the `HasRoles` trait is also mentioned:

![image](https://user-images.githubusercontent.com/1162360/221365046-2a37e48c-2741-47d7-a721-4f5a6b9c566b.png)

But if you see an invalid reference in the documentation (which is possible of course) I would be grateful for a PR with the fix here: https://github.com/vanilophp/docs

Thank you! :pray:

**Comment by MallauryGerard** [comment]
Ok thanks! You're right.

I firstly extended "\Konekt\User\Models\User" and did not change it...

**Comment by fulopattila122** [comment]
Yes, `\Konekt\User\Models\User` is the "root" model; it wasn't far from the truth :wink:
