### ISSUE TITLE
How to convert property to multiselect

### ISSUE THREAD

**Issue by arunjoseph02** [vanilophp/admin#6]
Hi this is not a bug, but a question, I wanted to know how can I convert the below select to multiselect?

I tried with custom properties, I was not able to find a solution

https://vanilo.io/docs/3.x/properties

```php
<?php

namespace App\Models;

class Size implements \Vanilo\Properties\Contracts\PropertyType
{
    public function getName(): string
    {
        return __('Size (S-XXL)');
    }

    public function transformValue(string $value, ?array $settings)
    {
        // @TODO - Fix here
        return 'S,M,XL';
    }
}
```

**Comment by arunjoseph02** [comment]
@fulopattila122 do you have any suggestions ?

**Comment by fulopattila122** [comment]
You don't have to create custom classes for each property, just create database entries for size:

![image](https://user-images.githubusercontent.com/1162360/235287276-32b7efaf-0bf0-4e5f-85aa-b4f6e80ef628.png)

and also values for them:

![image](https://user-images.githubusercontent.com/1162360/235287331-0e1e3b6e-34a1-4293-9075-f2e582b18b4d.png)
