### ISSUE TITLE
Is there any movement on the admin?

### ISSUE THREAD

**Issue by milosdakic** [vanilophp/admin#8]
I've noticed the admin package is a bit outdated. Is there any plans for a major overhaul

**Comment by fulopattila122** [comment]
What features are you looking for in particular?

**Comment by milosdakic** [comment]
It seems the admin isn't being kept up to date with the core modules released eg. Adjustments.

**Comment by milosdakic** [comment]
I understand from Spree, these are applied to orders. And I'm guessing the incoming Promotions package is where people will be able to configure their promotions to apply adjustments?

**Comment by fulopattila122** [comment]
Yes, that is correct. We see shops built with Vanilo using adjustments such as shipping fees, taxes (per line item), promotions, and gift card payments.

Adjustments can be applied to basically any model that is "adjustable". Currently it can be cart, cart item, order and order item.

But the question was about the admin, if I'm not mistaken :smile:
Order level adjustments are already listed below the purchased items: https://github.com/vanilophp/admin/blob/master/Changelog.md#360

Is there anything else on the admin area you're missing in particular?
